
from django.urls import path

from .api import (
    AccountApiView,
    BannersApiView,
    BasketApiView,
    CatalogApiView,
    CategoriesApiView,
    LimitedProductsApiView,
    OrderApiView,
    OrdersApiView,
    PaymentApiView,
    PopularProductsApiView,
    ProductApiView,
    ProductReviewsApiView,
    ProfileApiView,
    ProfileAvatarApiView,
    ProfilePasswordApiView,
    SalesApiView,
    SignInApiView,
    SignOutApiView,
    SignUpApiView,
    TagsApiView,
)
from .views import (
    AboutPageView,
    AccountPageView,
    CartPageView,
    CatalogPageView,
    CheckoutPageView,
    HomePageView,
    OrderDetailPageView,
    OrderHistoryPageView,
    PaymentPageView,
    PaymentSomeonePageView,
    ProductPageView,
    ProfilePageView,
    SalePageView,
    SignInPageView,
    SignUpPageView,
)

app_name = "shopapp"

urlpatterns = [
    path("", HomePageView.as_view(), name="index"),
    path("about/", AboutPageView.as_view(), name="about"),
    path("account/", AccountPageView.as_view(), name="account"),
    path("cart/", CartPageView.as_view(), name="cart"),
    path("catalog/", CatalogPageView.as_view(), name="catalog"),
    path("catalog/<int:category_id>/", CatalogPageView.as_view(), name="catalog_by_category"),
    path("history-order/", OrderHistoryPageView.as_view(), name="history_order"),
    path("orders/<int:order_id>/", CheckoutPageView.as_view(), name="order"),
    path("order-detail/<int:order_id>/", OrderDetailPageView.as_view(), name="order_detail"),
    path("payment/<int:order_id>/", PaymentPageView.as_view(), name="payment"),
    path("payment-someone/", PaymentSomeonePageView.as_view(), name="payment_someone"),
    path("product/<int:product_id>/", ProductPageView.as_view(), name="product_detail"),
    path("profile/", ProfilePageView.as_view(), name="profile"),
    path("sale/", SalePageView.as_view(), name="sale"),
    path("sign-in/", SignInPageView.as_view(), name="sign_in"),
    path("sign-up/", SignUpPageView.as_view(), name="sign_up"),
    path("api/categories/", CategoriesApiView.as_view(), name="api_categories"),
    path("api/basket/", BasketApiView.as_view(), name="api_basket"),
    path("api/banners", BannersApiView.as_view(), name="api_banners"),
    path("api/products/popular/", PopularProductsApiView.as_view(), name="api_products_popular"),
    path("api/products/limited/", LimitedProductsApiView.as_view(), name="api_products_limited"),
    path("api/tags/", TagsApiView.as_view(), name="api_tags"),
    path("api/catalog/", CatalogApiView.as_view(), name="api_catalog"),
    path("api/product/<int:product_id>/", ProductApiView.as_view(), name="api_product"),
    path("api/product/<int:product_id>/reviews/", ProductReviewsApiView.as_view(), name="api_product_reviews"),
    path("api/orders/", OrdersApiView.as_view(), name="api_orders"),
    path("api/order/<int:order_id>/", OrderApiView.as_view(), name="api_order"),
    path("api/payment/<int:order_id>/", PaymentApiView.as_view(), name="api_payment"),
    path("api/profile/", ProfileApiView.as_view(), name="api_profile"),
    path("api/profile/password/", ProfilePasswordApiView.as_view(), name="api_profile_password"),
    path("api/profile/avatar/", ProfileAvatarApiView.as_view(), name="api_profile_avatar"),
    path("api/account/", AccountApiView.as_view(), name="api_account"),
    path("api/sign-in/", SignInApiView.as_view(), name="api_sign_in"),
    path("api/sign-up/", SignUpApiView.as_view(), name="api_sign_up"),
    path("api/sign-out/", SignOutApiView.as_view(), name="api_sign_out"),
    path("api/sales/", SalesApiView.as_view(), name="api_sales"),
]
