# Generated by Django 6.0.4 on 2026-04-17 00:00

import shopapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0008_order_promo_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to=shopapp.models.product_image_upload_to,
                verbose_name="Изображение",
            ),
        ),
    ]